spring.application.name=eraapi

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/era_db_estoque}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:vini}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:era123}

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:true}
spring.flyway.locations=${SPRING_FLYWAY_LOCATIONS:classpath:db/migration}
